version: "3"
services:
  nginx_web:
    image: ww7849258/blade_nginx:1.2.0
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - internal-blade
    links:
      - blade_app1
      - blade_app2
    restart: unless-stopped
  blade_app1:
    image: ww7849258/blade:1.2.1
    environment:
      - "DATABASE_USERNAME=root"
      - "DATABASE_PASSWORD=root"
      - "DATABASE_HOST=blade-db"
      - "DATABASE_DB_NAME=blade"
      - "RAILS_ENV=staging"
      - "REDIS_HOST=blade-redis"
    ports:
      - "4001:80"
    links:
      - blade-db
    networks:
      - internal-blade
    restart: unless-stopped
  blade_app2:
    image: ww7849258/blade:1.2.1
    environment:
      - "DATABASE_USERNAME=root"
      - "DATABASE_PASSWORD=root"
      - "DATABASE_HOST=blade-db"
      - "DATABASE_DB_NAME=blade"
      - "RAILS_ENV=staging"
      - "REDIS_HOST=blade-redis"
    ports:
      - "4002:80"
    links:
      - blade-db
    networks:
      - internal-blade
    restart: unless-stopped
  blade-db:
    image: mysql:5.6
    ports:
      - "33306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=0.0.0.0
    volumes:
      - ./blade_db:/data
      - db-data:/var/lib/mysql
    networks:
      - internal-blade
    restart: unless-stopped
  blade-redis:
    image: redis
    ports:
      - "36379:6379"
    networks:
      - internal-blade  
    restart: unless-stopped
networks:
  internal-blade:
volumes:
  db-data:
